Repository eclipse-che/che-dashboard, pull requests merged in 2021-09, with the labels that each got.

#331 feat: provides CHE_PLUGIN_REGISTRY_INTERNAL_URL into devContainers
  packages/dashboard-frontend/src/services/workspace-client/devWorkspaceClient.ts
  packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
  packages/dashboard-frontend/src/store/Workspaces/index.ts
Labels: lgtm

#334 Fix links for branding related resources.
  README.md
Labels: lgtm

#336 fix: prevent crashing UD
  packages/dashboard-frontend/src/services/workspace-client/cheWorkspaceClient.ts
  packages/dashboard-frontend/src/services/workspace-client/devWorkspaceClient.ts
  packages/dashboard-frontend/src/services/workspaceAdapter/helper.ts
  packages/dashboard-frontend/src/services/workspaceAdapter/index.ts
Labels: lgtm

#339 docs: fix command
  README.md
Labels: lgtm

#342 Bump version to 7.37.0-SNAPSHOT
  .deps/EXCLUDED/prod.md
  lerna.json
  package.json
  packages/dashboard-backend/package.json
  packages/dashboard-frontend/package.json
  packages/static-server/package.json
Labels: lgtm

#343 Fix factory error messages
  packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx
  packages/dashboard-frontend/src/services/helpers/getErrorMessage.ts
Labels: lgtm

#344 fix: Fix wrong devfile doc url
  packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts
Labels: needs-ok-to-test, lgtm

#347 Suggest devfile v2 template when enabling DevWorkspaces
  packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx
  packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/index.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/StorageType/index.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/index.tsx
  packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/GetStartedTab.spec.tsx
  packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/index.tsx
  packages/dashboard-frontend/src/pages/GetStarted/__tests__/GetStarted.spec.tsx
  packages/dashboard-frontend/src/pages/GetStarted/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/__tests__/Actions.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx
  packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts
  packages/dashboard-frontend/src/services/devfileApi/devfile/index.ts
  packages/dashboard-frontend/src/services/devfileApi/typeguards.ts
  packages/dashboard-frontend/src/services/storageTypes.ts
  packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts
  packages/dashboard-frontend/src/services/workspace-adapter/helper.ts
  packages/dashboard-frontend/src/services/workspace-adapter/index.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
  packages/dashboard-frontend/src/store/FactoryResolver/getDevfile.ts
  packages/dashboard-frontend/src/store/InfrastructureNamespaces/selectors.ts
  packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts
  packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
  packages/dashboard-frontend/src/store/Workspaces/index.ts
  packages/dashboard-frontend/src/store/Workspaces/selectors.ts
  packages/dashboard-frontend/src/store/__mocks__/cheWorkspaceBuilder.ts
  packages/dashboard-frontend/src/store/__mocks__/devWorkspaceBuilder.ts
Labels: lgtm

#345 Fix ability to modify devworkspaces
  packages/dashboard-backend/jest.config.js
  packages/dashboard-backend/src/api/devworkspaceApi.ts
  packages/dashboard-backend/src/constants/examples.ts
  packages/dashboard-backend/src/constants/schemas.ts
  packages/dashboard-backend/src/devworkspace-client/__tests__/integration.spec.ts
  packages/dashboard-backend/src/devworkspace-client/services/api/workspace-api.ts
  packages/dashboard-backend/src/devworkspace-client/services/converters/index.ts
  packages/dashboard-backend/src/devworkspace-client/types/index.ts
  packages/dashboard-backend/src/typings/models.d.ts
  packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/index.tsx
  packages/dashboard-frontend/src/pages/WorkspacesList/Rows.tsx
  packages/dashboard-frontend/src/services/dashboard-backend-client/devWorkspaceApi.ts
  packages/dashboard-frontend/src/services/workspace-adapter/helper.ts
  packages/dashboard-frontend/src/services/workspace-adapter/index.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/converter.spec.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/sample-devfile-plugins.yaml
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/sample-devfile.yaml
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/sample-devworkspace.yaml
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/sample-dwt.yaml
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
  packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
  packages/dashboard-frontend/src/store/__mocks__/devWorkspaceBuilder.ts
Labels: lgtm

#350 feat: Handle custom editor in repository or inlined in devfile
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
  packages/dashboard-frontend/src/store/FactoryResolver/index.ts
Labels: lgtm

#348 feat: make backend respect internal URL, CAs and http proxy settings
  .deps/dev.md
  .deps/problems.md
  .deps/prod.md
  packages/dashboard-backend/package.json
  packages/dashboard-backend/src/services/che-http/CertsProvider.ts
  packages/dashboard-backend/src/services/che-http/CheAxiosFactory.ts
  packages/dashboard-backend/src/services/kubeclient/keycloak.ts
  packages/dashboard-backend/tslint.json
  yarn.lock
Labels: lgtm

#352 Prevent changing name and namespace of devworkspace in the devfile-editor for existing workspaces
  packages/dashboard-backend/src/index.ts
  packages/dashboard-backend/src/local-run/index.ts
  packages/dashboard-backend/src/services/kubeclient/keycloak.ts
  packages/dashboard-backend/src/static.ts
  packages/dashboard-frontend/package.json
  packages/dashboard-frontend/src/components/DevfileEditor/index.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/WorkspaceName/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/WorkspaceName/index.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/index.tsx
  packages/dashboard-frontend/src/services/bootstrap/PreloadData.ts
  packages/dashboard-frontend/src/store/DevfileRegistries/index.ts
  packages/dashboard-frontend/webpack.config.common.js
  packages/dashboard-frontend/webpack.config.dev.js
  packages/dashboard-frontend/webpack.config.prod-dev.js
Labels: lgtm

#323 feat: Make che-dashboard installable to support ctrl-w etc
  packages/dashboard-frontend/assets/branding/manifest.json
  packages/dashboard-frontend/index.html
  packages/dashboard-frontend/src/index.tsx
  packages/dashboard-frontend/src/service-worker.ts
  packages/dashboard-frontend/webpack.config.common.js
Labels: needs-ok-to-test

#357 Add namespace provision request
  .deps/EXCLUDED/prod.md
  .deps/prod.md
  packages/common/package.json
  packages/dashboard-backend/package.json
  packages/dashboard-backend/src/api/cheApi.ts
  packages/dashboard-backend/src/index.ts
  packages/dashboard-frontend/package.json
  packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/InfrastructureNamespace/__tests__/InfrastructureNamespaceSelect.spec.tsx
  packages/dashboard-frontend/src/services/bootstrap/PreloadData.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
  packages/dashboard-frontend/src/store/FactoryResolver/index.ts
  packages/dashboard-frontend/src/store/InfrastructureNamespaces/index.ts
  yarn.lock
Labels: lgtm

#356 fix: avoid potential npe
  packages/dashboard-backend/src/devworkspace-client/services/api/workspace-api.ts
Labels: lgtm

#359 fix: make-release now respect up to date common package
  .deps/prod.md
  make-release.sh
Labels: lgtm

#363 chore: change PR check image repository to quay.io
  .github/workflows/pr.yml
Labels: lgtm

#362 Fix updating branding data
  packages/dashboard-frontend/src/store/Branding/index.ts
Labels: bug, lgtm

#364 Fix updating branding data
  packages/dashboard-frontend/src/store/Branding/index.ts
Labels: lgtm

#367 Bump version of @eclipse-che/che-theia-devworkspace-handler to the latest released
  packages/dashboard-frontend/package.json
Labels: lgtm

#366 Bump version of @eclipse-che/che-theia-devworkspace-handler to the latest released
  packages/dashboard-frontend/package.json
Labels: lgtm
