Repository eclipse-che/che-dashboard, pull requests merged in 2022-02, with the labels that each got.

#450 Decrease workspaces converting time
  .deps/dev.md
  .deps/prod.md
  README.md
  packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Labels: lgtm

#453 Provide devfile parent section to a new devworkspace
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/converter.spec.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/test-devfile-parent.yaml
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/test-devworkspace-parent.yaml
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/index.ts
Labels: lgtm

#454 fix: generateName is not executed if devfile v2
  packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx
  packages/dashboard-frontend/src/services/devfileApi/devfile/metadata.ts
  packages/dashboard-frontend/src/services/devfileApi/typeguards.ts
Labels: needs-ok-to-test, lgtm

#452 Prevent infinite reloads loop
  packages/dashboard-backend/src/local-run/che-server.ts
  packages/dashboard-frontend/src/containers/FactoryLoader/__tests__/FactoryLoader.privateRepo.spec.tsx
  packages/dashboard-frontend/src/containers/FactoryLoader/__tests__/FactoryLoader.spec.tsx
  packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx
  packages/dashboard-frontend/src/services/session-storage/index.ts
Labels: lgtm

#456 "Delete Workspace" button for deprecated workspaces
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/Button.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/Dropdown/index.module.css
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/Dropdown/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/index.tsx
Labels: lgtm

#458 fix: skip DevWorkspaceTemplate updates for sidecarless editors (che-code)
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Labels: lgtm, ok-to-test

#459 Hide the "Convert" button when conversion is done
  packages/dashboard-frontend/src/Layout/Navigation/MainList.tsx
  packages/dashboard-frontend/src/Layout/Navigation/__tests__/MainList.spec.tsx
  packages/dashboard-frontend/src/containers/WorkspaceDetails.tsx
  packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.conversion.spec.tsx
  packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx
  packages/dashboard-frontend/src/containers/WorkspacesList.tsx
  packages/dashboard-frontend/src/containers/__tests__/WorkspacesList.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/ConversionButton/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/ConversionButton/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/__mocks__/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/InlineAlerts/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/InlineAlerts/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/StorageType/__mocks__/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/StorageType/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/__mocks__/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/index.tsx
  packages/dashboard-frontend/src/typings/che.d.ts
Labels: lgtm

#462 Bump codecov-action
  .github/workflows/codecov.yml
Labels: lgtm

#461 Add annotation with workspace ID
  packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.conversion.spec.tsx
  packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx
  packages/dashboard-frontend/src/containers/WorkspacesList.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/index.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/WorkspaceDetails/index.tsx
  packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts
Labels: lgtm

#465 fix: Fix some devfile v1 to v2 conversions
  .deps/prod.md
  packages/dashboard-frontend/package.json
  yarn.lock
Labels: lgtm

#464 Add plugin registry environment variables (#446)
  packages/dashboard-frontend/src/services/workspace-adapter/index.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
  packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Labels: lgtm
