Repository eclipse-che/che-dashboard, pull requests merged in 2024-03, with the labels that each got.

#1060 chore: update dockerfile
  build/dockerfiles/Dockerfile
  build/dockerfiles/skaffold.Dockerfile
Labels: lgtm

#1061 Update the tools container image
  devfile.yaml
Labels: lgtm, made-with-che

#1069 fix: normalizeDevfileV1 method
  packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV1.spec.ts
  packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV1.ts
Labels: lgtm

#1067 fix: fix release causing dependency inconsistency
  .github/workflows/release.yml
  make-release.sh
Labels: lgtm

#1071 Fix workspace start from Bitbucket server repository with OAuth2
  packages/dashboard-backend/src/routes/__tests__/factoryAcceptanceRedirect.spec.ts
  packages/dashboard-backend/src/routes/factoryAcceptanceRedirect.ts
  packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
Labels: lgtm

#1068 Add gitlab to the list of allowed to revoke oauth providers
  packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/index.tsx
Labels: lgtm

#1070 chore: update actions to use Node.js 20
  .github/workflows/codecov.yml
  .github/workflows/next-build-multiarch.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: lgtm

#1066 fix: remove deprecated package
  .deps/dev.md
  .deps/prod.md
  packages/dashboard-backend/package.json
  yarn.lock
Labels: lgtm

#1076 Bump dependencies
  .deps/prod.md
  yarn.lock
Labels: lgtm

#1072 Sanitize the git provider endpoint
  packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/__tests__/helpers.spec.ts
  packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/helpers.ts
  packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/__tests__/__snapshots__/index.spec.tsx.snap
  packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/index.tsx
Labels: lgtm

#1078 Fix cors issue when fetching editor devfile
  packages/dashboard-frontend/src/services/backend-client/__tests__/yamlResolverApi.spec.ts
  packages/dashboard-frontend/src/services/backend-client/yamlResolverApi.ts
  packages/dashboard-frontend/src/services/bootstrap/__tests__/index.spec.tsx
  packages/dashboard-frontend/src/services/registry/__tests__/fetchData.spec.ts
  packages/dashboard-frontend/src/services/registry/fetchData.ts
  packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts
  packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/getEditor.spec.ts
  packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/index.spec.ts
  packages/dashboard-frontend/src/store/DevfileRegistries/index.ts
  packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts
  packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts
Labels: made-with-che
